# Forge 1.20.1 server settings. Rebuild and redeploy after editing.
motd=\u00a7e\u2622 AQLabs \u00a7bForge Server \u00a7e\u2622
server-ip=
server-port=25565
online-mode=true
enforce-secure-profile=true
max-players=4
white-list=false
enforce-whitelist=false

gamemode=survival
force-gamemode=false
difficulty=normal
hardcore=false
allow-flight=true
pvp=true
allow-nether=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
enable-command-block=false
op-permission-level=4
function-permission-level=2

level-name=world
level-seed=
level-type=minecraft\:normal
generator-settings={}
generate-structures=true
max-world-size=29999984

view-distance=10
simulation-distance=6
max-tick-time=60000
network-compression-threshold=256
player-idle-timeout=0
sync-chunk-writes=true
entity-broadcast-range-percentage=100

enable-status=true
hide-online-players=false
enable-query=false
query.port=25565
enable-rcon=true
rcon.port=25575
rcon.password=${CFG_RCON_PASSWORD}
broadcast-rcon-to-ops=false
broadcast-console-to-ops=true
enable-jmx-monitoring=false
prevent-proxy-connections=false
use-native-transport=true

resource-pack=
resource-pack-sha1=
resource-pack-prompt=
require-resource-pack=false
